### ISSUE TITLE
Add configuration

### ISSUE THREAD

**Issue by jbcr** [code-rhapsodie/SyliusElasticsearchPlugin#6]
Doc: https://symfony.com/doc/current/bundles/configuration.html

This parameters value must be provided by bundle configuration:

* bitbag_es_excluded_filter_options : `string[]`, required: false, default value: `[]`
* bitbag_es_excluded_filter_attributes : `string[]`, required: false, default value: `[]`
* bitbag_es_filter_attributes_max: `integer`, required: false, default value: `20`
* bitbag_es_filter_options_max : `integer`, required: false, default value: `20`
* bitbag_es_shop_name_property_prefix: `string`, requied: false, default value: `sylius`

Expected configuration:

```yaml
bit_bag_sylius_elasticsearch:
    excluded_filter:
        options: ['option1', 'option2']
        attribute:
            - attribute1
            - attribute2
    filter_attributes_max: 20
    filter_options_max: 20
    shop_name_property_prefix: sylius
```

Doc for add parameter before the extension loading: https://symfony.com/doc/current/components/dependency_injection/compilation.html#prepending-configuration-passed-to-the-extension
